# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-23 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario', models.CharField(max_length=250)),
                ('Estrellas', models.IntegerField(verbose_name=b'estrella')),
                ('Comentario', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Etiquetas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dia', models.CharField(max_length=250)),
                ('Hora_Inicial', models.TimeField()),
                ('Hora_Final', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagen', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=250)),
                ('Estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrador.Estados')),
            ],
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=250)),
                ('A_Paterno', models.CharField(max_length=250)),
                ('A_Materno', models.CharField(max_length=250)),
                ('Foto', models.FilePathField(max_length=250)),
                ('Giro', models.CharField(max_length=250)),
                ('Correo_Electronico', models.EmailField(max_length=254)),
                ('Telefono', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=250)),
                ('Precio', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Promociones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion_Corta', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=250)),
                ('Imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrador.Imagenes')),
            ],
        ),
        migrations.CreateModel(
            name='Redes_Sociales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Facebook', models.CharField(max_length=250)),
                ('Twitter', models.CharField(max_length=250)),
                ('Instagram', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tiendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=250)),
                ('Logo', models.FilePathField()),
                ('Lema', models.CharField(max_length=250)),
                ('Descripcion', models.CharField(max_length=250)),
                ('Direccion', models.CharField(max_length=250)),
                ('Latitud', models.CharField(max_length=250)),
                ('Longitud', models.CharField(max_length=250)),
                ('Telefono', models.CharField(max_length=250)),
                ('Cotizacion', models.BooleanField(default=False)),
                ('Cotizacion_Dato', models.CharField(blank=True, max_length=250)),
                ('Precio_Mayoreo', models.BooleanField(default=False)),
                ('Etiqueta', models.ManyToManyField(to='Administrador.Etiquetas')),
                ('Horario', models.ManyToManyField(to='Administrador.Horarios')),
                ('Redes_Sociales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrador.Redes_Sociales')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Tienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='tiendas',
            name='Tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrador.Tipo_Tienda'),
        ),
        migrations.AddField(
            model_name='promociones',
            name='Tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrador.Tiendas'),
        ),
        migrations.AddField(
            model_name='productos',
            name='Tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrador.Tiendas'),
        ),
        migrations.AddField(
            model_name='personas',
            name='Tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrador.Tiendas'),
        ),
        migrations.AddField(
            model_name='imagenes',
            name='Tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrador.Tiendas'),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='Tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrador.Tiendas'),
        ),
    ]
